/* Generated By:JavaCC: Do not edit this line. ProjLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 5;
  /** RegularExpression Id. */
  int RPAREN = 6;
  /** RegularExpression Id. */
  int SEMICOL = 7;
  /** RegularExpression Id. */
  int LBRACES = 8;
  /** RegularExpression Id. */
  int RBRACES = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int NOTEQUALS = 11;
  /** RegularExpression Id. */
  int FUNC = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int THEN = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int LET = 18;
  /** RegularExpression Id. */
  int VAL = 19;
  /** RegularExpression Id. */
  int IN = 20;
  /** RegularExpression Id. */
  int END = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int EQUAL = 24;
  /** RegularExpression Id. */
  int ID = 25;
  /** RegularExpression Id. */
  int NUM = 26;
  /** RegularExpression Id. */
  int ADDOP = 27;
  /** RegularExpression Id. */
  int MULOP = 28;
  /** RegularExpression Id. */
  int RELOP = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"{\"",
    "\"}\"",
    "\":=\"",
    "\"!\"",
    "\"fun\"",
    "\"while\"",
    "\"do\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"val\"",
    "\"in\"",
    "\"end\"",
    "\"true\"",
    "\"false\"",
    "\"=\"",
    "<ID>",
    "<NUM>",
    "<ADDOP>",
    "<MULOP>",
    "\"<\"",
  };

}
